on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: PR Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: npm install for mock project
        run: npm install
        working-directory: task/src/__mock__

      - name: npm install
        run: npm install
        working-directory: task/src
      - name: npm test
        run: npm test
        working-directory: task/src

      - name: PR Landmine
        uses: tylermurry/github-pr-landmine@v1
        with:
          token: ${{ github.token }}
          test-command: 'npm test'
          test-command-directory: 'task/src'
